db.dishes.insertMany([
  // --- 凉菜 (Cold Dishes) ---
  { "name": "拍黄瓜", "price": 18, "description": "清爽开胃的凉菜", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 5, "tags": ["凉菜", "素食", "不辣", "性价比", "清爽"] },
  { "name": "夫妻肺片", "price": 48, "description": "麻辣鲜香的经典川菜", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 10, "tags": ["凉菜", "辣", "牛肉", "重口味", "经典"] },
  { "name": "蓝莓山药", "price": 32, "description": "健康营养的甜品", "isDelisted": false, "isSpicy": false, "hasScallions": false, "hasCilantro": false, "hasGarlic": false, "cookingTime": 8, "tags": ["凉菜", "素食", "不辣", "爸妈", "儿童", "甜品"] },
  { "name": "老醋花生", "price": 22, "description": "酸甜可口的下酒菜", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": false, "cookingTime": 5, "tags": ["凉菜", "素食", "不辣", "下酒", "性价比"] },
  { "name": "酱牛肉", "price": 68, "description": "酱香浓郁的牛肉", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 120, "tags": ["凉菜", "牛肉", "不辣", "带领导", "硬菜"] },
  { "name": "剁椒荷包蛋", "price": 28, "description": "香辣下饭", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": false, "hasGarlic": true, "cookingTime": 8, "tags": ["凉菜", "辣", "性价比", "下饭"] },
  { "name": "白灼菜心", "price": 26, "description": "清淡健康", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": false, "hasGarlic": true, "cookingTime": 6, "tags": ["凉菜", "素食", "不辣", "健康", "爸妈"] },
  { "name": "口水鸡", "price": 45, "description": "麻辣鲜香的鸡肉", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 15, "tags": ["凉菜", "辣", "鸡肉", "相亲", "热门"] },
  { "name": "五香熏鱼", "price": 52, "description": "甜口熏鱼", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": false, "hasGarlic": false, "cookingTime": 30, "tags": ["凉菜", "鱼", "不辣", "带领导", "甜口"] },
  { "name": "凉拌海蜇", "price": 58, "description": "清爽脆嫩", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 10, "tags": ["凉菜", "海鲜", "不辣", "清爽", "带领导"] },
  { "name": "冰镇秋葵", "price": 35, "description": "健康养生", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": false, "hasGarlic": true, "cookingTime": 8, "tags": ["凉菜", "素食", "不辣", "健康", "相亲"] },
  { "name": "爽口木耳", "price": 24, "description": "清脆可口", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 10, "tags": ["凉菜", "素食", "不辣", "健康", "清真"] },
  { "name": "皮蛋豆腐", "price": 20, "description": "嫩滑可口", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 5, "tags": ["凉菜", "素食", "不辣", "性价比", "滑嫩"] },
  { "name": "麻辣牛板筋", "price": 42, "description": "麻辣Q弹", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 90, "tags": ["凉菜", "辣", "牛肉", "下酒"] },
  { "name": "泡椒凤爪", "price": 38, "description": "酸辣爽口", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": false, "hasGarlic": true, "cookingTime": 60, "tags": ["凉菜", "辣", "鸡肉", "零食"] },
  { "name": "素什锦", "price": 28, "description": "清爽健康", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 10, "tags": ["凉菜", "素食", "不辣", "清真", "健康"] },
  { "name": "桂花糯米藕", "price": 36, "description": "软糯香甜", "isDelisted": false, "isSpicy": false, "hasScallions": false, "hasCilantro": false, "hasGarlic": false, "cookingTime": 45, "tags": ["凉菜", "素食", "不辣", "爸妈", "甜口"] },
  { "name": "泰式酸辣凤爪", "price": 46, "description": "酸辣开胃", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 60, "tags": ["凉菜", "辣", "鸡肉", "相亲"] },
  { "name": "红油肚丝", "price": 55, "description": "麻辣爽脆", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 15, "tags": ["凉菜", "辣", "猪肉", "下酒", "硬菜"] },
  { "name": "温拌海螺片", "price": 88, "description": "鲜嫩高级", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 12, "tags": ["凉菜", "海鲜", "不辣", "带领导", "高级"] },
  { "name": "芥末鸭掌", "price": 48, "description": "爽脆开胃", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": false, "hasGarlic": false, "cookingTime": 30, "tags": ["凉菜", "辣", "鸭肉", "带领导"] },
  { "name": "捞汁什锦海鲜", "price": 78, "description": "鲜美丰富", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 15, "tags": ["凉菜", "海鲜", "辣", "相亲", "热门"] },
  { "name": "拌腐竹", "price": 22, "description": "清淡健康", "isDelisted": false, "isSpicy": false, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 8, "tags": ["凉菜", "素食", "不辣", "清真", "健康"] },
  { "name": "蒜泥白肉", "price": 42, "description": "蒜香浓郁", "isDelisted": false, "isSpicy": true, "hasScallions": true, "hasCilantro": true, "hasGarlic": true, "cookingTime": 20, "tags": ["凉菜", "辣", "猪肉", "下饭"] },
  { "name": "糖拌西红柿", "price": 15, "description": "酸甜清爽", "isDelisted": false, "isSpicy": false, "hasScallions": false, "hasCilantro": false, "hasGarlic": false, "cookingTime": 3, "tags": ["凉菜", "素食", "不辣", "儿童", "性价比"] },

  // --- 热菜 (Hot Dishes) - 肉类 ---
  { "name": "红烧肉", "price": 78, "tags": ["热菜", "猪肉", "不辣", "爸妈", "硬菜"] },
  { "name": "宫保鸡丁", "price": 38, "tags": ["热菜", "鸡肉", "辣", "性价比", "经典"] },
  { "name": "清蒸石斑鱼", "price": 188, "tags": ["热菜", "鱼", "不辣", "带领导", "高级", "健康"] },
  { "name": "水煮鱼", "price": 98, "tags": ["热菜", "鱼", "辣", "热门", "重口味"] },
  { "name": "小炒肉", "price": 45, "tags": ["热菜", "猪肉", "辣", "下饭", "性价比"] },
  { "name": "京酱肉丝", "price": 52, "tags": ["热菜", "猪肉", "不辣", "儿童", "经典"] },
  { "name": "羊肉串(盘)", "price": 88, "tags": ["热菜", "羊肉", "辣", "清真", "下酒"] },
  { "name": "葱爆羊肉", "price": 75, "tags": ["热菜", "羊肉", "不辣", "清真", "爸妈"] },
  { "name": "避风塘炒蟹", "price": 258, "tags": ["热菜", "海鲜", "辣", "带领导", "高级"] },
  { "name": "油焖大虾", "price": 128, "tags": ["热菜", "海鲜", "不辣", "相亲", "硬菜"] },
  { "name": "黑椒牛柳", "price": 88, "tags": ["热菜", "牛肉", "辣", "相亲", "西式"] },
  { "name": "酸菜鱼", "price": 88, "tags": ["热菜", "鱼", "辣", "热门", "爸妈"] },
  { "name": "回锅肉", "price": 48, "tags": ["热菜", "猪肉", "辣", "经典", "下饭"] },
  { "name": "蒜香排骨", "price": 72, "tags": ["热菜", "猪肉", "不辣", "儿童", "硬菜"] },
  { "name": "糖醋里脊", "price": 42, "tags": ["热菜", "猪肉", "不辣", "儿童", "性价比"] },
  { "name": "铁板鲈鱼", "price": 98, "tags": ["热菜", "鱼", "不辣", "相亲", "氛围感"] },
  { "name": "红烧狮子头", "price": 58, "tags": ["热菜", "猪肉", "不辣", "爸妈", "硬菜"] },
  { "name": "辣子鸡", "price": 55, "tags": ["热菜", "鸡肉", "特辣", "下酒", "重口味"] },
  { "name": "小龙虾(麻辣)", "price": 168, "tags": ["热菜", "海鲜", "特辣", "热门", "下酒"] },
  { "name": "鲍鱼红烧肉", "price": 158, "tags": ["热菜", "猪肉", "海鲜", "不辣", "带领导", "高级"] },
  { "name": "鱼香肉丝", "price": 38, "tags": ["热菜", "猪肉", "辣", "性价比", "热门"] },
  { "name": "麻婆豆腐", "price": 28, "tags": ["热菜", "素食", "辣", "经典", "性价比"] },
  { "name": "干锅花菜", "price": 32, "tags": ["热菜", "素食", "辣", "热门", "性价比"] },
  { "name": "地三鲜", "price": 28, "tags": ["热菜", "素食", "不辣", "爸妈", "经典"] },
  { "name": "手撕包菜", "price": 25, "tags": ["热菜", "素食", "辣", "性价比", "下饭"] },
  { "name": "西红柿炒鸡蛋", "price": 22, "tags": ["热菜", "素食", "不辣", "儿童", "性价比"] },
  { "name": "蚝油生菜", "price": 20, "tags": ["热菜", "素食", "不辣", "健康", "清真"] },
  { "name": "荷塘小炒", "price": 38, "tags": ["热菜", "素食", "不辣", "健康", "相亲"] },
  { "name": "腰果虾仁", "price": 98, "tags": ["热菜", "海鲜", "不辣", "相亲", "健康"] },
  { "name": "松鼠鳜鱼", "price": 198, "tags": ["热菜", "鱼", "不辣", "带领导", "硬菜", "甜口"] },
  { "name": "红烧茄子", "price": 32, "tags": ["热菜", "素食", "不辣", "爸妈", "经典"] },
  { "name": "荷兰豆炒腊肉", "price": 48, "tags": ["热菜", "猪肉", "不辣", "健康", "清爽"] },
  { "name": "毛血旺", "price": 88, "tags": ["热菜", "猪肉", "特辣", "硬菜", "重口味"] },
  { "name": "干煸豆角", "price": 35, "tags": ["热菜", "素食", "辣", "经典", "下酒"] },
  { "name": "咖喱鸡块", "price": 48, "tags": ["热菜", "鸡肉", "辣", "儿童", "下饭"] },
  { "name": "烧蹄筋", "price": 128, "tags": ["热菜", "猪肉", "不辣", "带领导", "滋补"] },
  { "name": "清炒虾仁", "price": 88, "tags": ["热菜", "海鲜", "不辣", "清真", "健康"] },
  { "name": "梅菜扣肉", "price": 68, "tags": ["热菜", "猪肉", "不辣", "爸妈", "硬菜"] },
  { "name": "香辣美容蹄", "price": 78, "tags": ["热菜", "猪肉", "辣", "热门", "女性"] },
  { "name": "蚂蚁上树", "price": 32, "tags": ["热菜", "猪肉", "辣", "经典", "性价比"] },
  { "name": "菠萝咕噜肉", "price": 52, "tags": ["热菜", "猪肉", "不辣", "儿童", "相亲"] },
  { "name": "蒜茸粉丝蒸扇贝", "price": 120, "tags": ["热菜", "海鲜", "不辣", "带领导", "热门"] },
  { "name": "木须肉", "price": 38, "tags": ["热菜", "猪肉", "不辣", "清真", "经典"] },
  { "name": "豆豉鲮鱼油麦菜", "price": 35, "tags": ["热菜", "素食", "不辣", "经典", "健康"] },
  { "name": "剁椒鱼头", "price": 108, "tags": ["热菜", "鱼", "辣", "硬菜", "热门"] },
  { "name": "东坡肉", "price": 45, "tags": ["热菜", "猪肉", "不辣", "带领导", "经典"] },
  { "name": "爆炒腰花", "price": 65, "tags": ["热菜", "猪肉", "辣", "硬菜", "下酒"] },
  { "name": "孜然牛肉", "price": 78, "tags": ["热菜", "牛肉", "辣", "清真", "下酒"] },
  { "name": "家常豆腐", "price": 26, "tags": ["热菜", "素食", "不辣", "爸妈", "性价比"] },
  { "name": "上汤娃娃菜", "price": 38, "tags": ["热菜", "素食", "不辣", "爸妈", "汤菜"] },
  { "name": "湘式小炒鸡", "price": 58, "tags": ["热菜", "鸡肉", "特辣", "下饭"] },

  // --- 汤品 (Soups) ---
  { "name": "西湖牛肉羹", "price": 48, "tags": ["汤", "牛肉", "不辣", "相亲", "经典"] },
  { "name": "酸辣汤", "price": 32, "tags": ["汤", "素食", "辣", "下饭", "性价比"] },
  { "name": "玉米排骨汤", "price": 68, "tags": ["汤", "猪肉", "不辣", "爸妈", "健康"] },
  { "name": "老鸭笋干汤", "price": 128, "tags": ["汤", "鸭肉", "不辣", "带领导", "滋补"] },
  { "name": "冬瓜虾米汤", "price": 35, "tags": ["汤", "海鲜", "不辣", "清爽", "性价比"] },
  { "name": "松茸土鸡汤", "price": 198, "tags": ["汤", "鸡肉", "不辣", "高级", "健康", "带领导"] },
  { "name": "蛤蜊豆腐汤", "price": 42, "tags": ["汤", "海鲜", "不辣", "清爽", "爸妈"] },
  { "name": "番茄牛腩汤", "price": 78, "tags": ["汤", "牛肉", "不辣", "热门", "儿童"] },
  { "name": "乌鸡白凤汤", "price": 158, "tags": ["汤", "鸡肉", "不辣", "滋补", "女性"] },
  { "name": "紫菜蛋花汤", "price": 18, "tags": ["汤", "素食", "不辣", "性价比", "经典"] },

  // --- 主食 (Staples) ---
  { "name": "扬州炒饭", "price": 38, "tags": ["主食", "不辣", "儿童", "经典"] },
  { "name": "牛肉拉面", "price": 28, "tags": ["主食", "牛肉", "不辣", "清真", "性价比"] },
  { "name": "猪肉大葱水饺", "price": 42, "tags": ["主食", "猪肉", "不辣", "爸妈", "经典"] },
  { "name": "海鲜面", "price": 58, "tags": ["主食", "海鲜", "不辣", "相亲", "丰富"] },
  { "name": "担担面", "price": 25, "tags": ["主食", "辣", "经典", "性价比"] },
  { "name": "腊肉炒粉", "price": 35, "tags": ["主食", "猪肉", "辣", "下饭"] },
  { "name": "白米饭", "price": 3, "tags": ["主食", "素食", "不辣", "必点"] },
  { "name": "黄金馒头", "price": 25, "tags": ["主食", "素食", "不辣", "儿童", "甜品"] },
  { "name": "葱油饼", "price": 18, "tags": ["主食", "素食", "不辣", "下酒", "经典"] },
  { "name": "素三鲜水饺", "price": 38, "tags": ["主食", "素食", "不辣", "健康", "清真"] },
  { "name": "干炒牛河", "price": 45, "tags": ["主食", "牛肉", "不辣", "经典", "热门"] },
  { "name": "麻酱凉面", "price": 22, "tags": ["主食", "素食", "不辣", "性价比", "清爽"] },
  { "name": "小笼包", "price": 35, "tags": ["主食", "猪肉", "不辣", "经典", "相亲"] },
  { "name": "红糖糍粑", "price": 28, "tags": ["主食", "素食", "不辣", "热门", "甜品"] }
])